import { useState, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Database } from '@/integrations/supabase/types';
import { toast } from 'sonner';

type ClaimType = Database['public']['Enums']['claim_type'];
type ClaimStatus = Database['public']['Enums']['claim_status'];
type ClaimRow = Database['public']['Tables']['claims']['Row'];
type ClaimInsert = Database['public']['Tables']['claims']['Insert'];

// Map from form type to database enum
const typeMapping: Record<string, ClaimType> = {
  'auto': 'automobile',
  'automobile': 'automobile',
  'habitation': 'habitation',
  'sante': 'sante',
  'vie': 'vie',
  'responsabilite_civile': 'responsabilite_civile',
  'autre': 'autre',
};

export interface CreateClaimData {
  policyNumber: string;
  type: string;
  description: string;
  incidentDate: Date;
  declarationDate: Date;
  location: string;
  estimatedAmount: number;
  declarantId: string;
  gestionnaireId?: string;
}

export function useClaimsDB() {
  const [isLoading, setIsLoading] = useState(false);

  const createClaim = useCallback(async (data: CreateClaimData) => {
    setIsLoading(true);
    try {
      const mappedType = typeMapping[data.type] || 'autre';
      
      const claimData: ClaimInsert = {
        policy_number: data.policyNumber,
        type: mappedType,
        description: data.description,
        incident_date: data.incidentDate.toISOString().split('T')[0],
        declaration_date: data.declarationDate.toISOString(),
        location: data.location,
        amount_claimed: data.estimatedAmount,
        declarant_id: data.declarantId,
        gestionnaire_id: data.gestionnaireId || null,
        claim_number: '', // Will be auto-generated by trigger
      };

      const { data: claim, error } = await supabase
        .from('claims')
        .insert(claimData)
        .select()
        .single();

      if (error) {
        console.error('Error creating claim:', error);
        throw error;
      }

      return claim;
    } finally {
      setIsLoading(false);
    }
  }, []);

  const createClaimEvent = useCallback(async (
    claimId: string,
    eventType: string,
    description: string,
    userId?: string
  ) => {
    const { error } = await supabase
      .from('claim_events')
      .insert({
        claim_id: claimId,
        event_type: eventType,
        description,
        user_id: userId || null,
      });

    if (error) {
      console.error('Error creating claim event:', error);
    }
  }, []);

  const uploadDocument = useCallback(async (
    claimId: string,
    file: File,
    userId: string
  ) => {
    try {
      // Upload to storage
      const fileExt = file.name.split('.').pop();
      const fileName = `${userId}/${claimId}/${Date.now()}.${fileExt}`;
      
      const { error: uploadError } = await supabase.storage
        .from('claim-documents')
        .upload(fileName, file);

      if (uploadError) {
        console.error('Error uploading file:', uploadError);
        throw uploadError;
      }

      // Get public URL
      const { data: urlData } = supabase.storage
        .from('claim-documents')
        .getPublicUrl(fileName);

      // Create document record
      const { error: docError } = await supabase
        .from('documents')
        .insert({
          claim_id: claimId,
          name: file.name,
          type: file.type,
          url: urlData.publicUrl,
          uploaded_by: userId,
        });

      if (docError) {
        console.error('Error creating document record:', docError);
        throw docError;
      }

      return urlData.publicUrl;
    } catch (error) {
      console.error('Error in uploadDocument:', error);
      throw error;
    }
  }, []);

  const fetchClaims = useCallback(async () => {
    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from('claims')
        .select(`
          *,
          declarant:profiles!claims_declarant_id_fkey(id, name, email, avatar),
          gestionnaire:profiles!claims_gestionnaire_id_fkey(id, name, email, avatar),
          expert:profiles!claims_expert_id_fkey(id, name, email, avatar)
        `)
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Error fetching claims:', error);
        throw error;
      }

      return data;
    } finally {
      setIsLoading(false);
    }
  }, []);

  const fetchClaimById = useCallback(async (id: string) => {
    const { data, error } = await supabase
      .from('claims')
      .select(`
        *,
        declarant:profiles!claims_declarant_id_fkey(id, name, email, avatar, phone),
        gestionnaire:profiles!claims_gestionnaire_id_fkey(id, name, email, avatar),
        expert:profiles!claims_expert_id_fkey(id, name, email, avatar),
        documents(*),
        claim_events(*, user:profiles(name, avatar))
      `)
      .eq('id', id)
      .maybeSingle();

    if (error) {
      console.error('Error fetching claim:', error);
      throw error;
    }

    return data;
  }, []);

  const updateClaimStatus = useCallback(async (
    claimId: string,
    status: ClaimStatus,
    userId?: string,
    description?: string
  ) => {
    const { error } = await supabase
      .from('claims')
      .update({ status })
      .eq('id', claimId);

    if (error) {
      console.error('Error updating claim status:', error);
      throw error;
    }

    // Create event
    if (userId) {
      await createClaimEvent(
        claimId,
        'status_change',
        description || `Statut changé vers ${status}`,
        userId
      );
    }
  }, [createClaimEvent]);

  return {
    isLoading,
    createClaim,
    createClaimEvent,
    uploadDocument,
    fetchClaims,
    fetchClaimById,
    updateClaimStatus,
  };
}
